services:
  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ottobon-landing-page
    ports:
      - "8085:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    network_mode: bridge
